---
- name: RHEL Base Configuration
  hosts: all
  gather_facts: true
  become: yes
  vars_files:
    - vars/parameters.yml
  
  roles:

    - role: configure-base-rhel
      tags: [allRoles, configure-base-rhel]

    - role: configure-ssh
      tags: [allRoles, configure-ssh]

    - role: configure-zram
      tags: [allRoles, configure-zram]

    - role: configure-snmp
      tags: [allRoles, configure-snmp]
